Integrating Auth0
Plant-for-the-Planet-org/treecounter-app pull request #2914
Opened 2020-12-22 09:47 UTC by harshvitra

Integrated library

2020-12-27 15:45 UTC, norbertschuler requested changes
Building staging app requires additional changes.

2020-12-27 15:45 UTC, norbertschuler commented on .github/workflows/ubuntu_build_android.yml
> +        cp .env.staging .env
If you want to build the staging app, you need to change https://github.com/Plant-for-the-Planet-org/treecounter-app/blob/1a759072ad5cb50ca50b386b7bd20f89d84099c4/.github/workflows/ubuntu_build_android.yml#L136 and https://github.com/Plant-for-the-Planet-org/treecounter-app/blob/1a759072ad5cb50ca50b386b7bd20f89d84099c4/.github/workflows/ubuntu_build_android.yml#L151 as well. (I have never tested it, so I am not sure if that's enough to change.)

2020-12-27 16:19 UTC, norbertschuler commented on .github/workflows/ubuntu_build_android.yml
> +        cp .env.staging .env
changed it

2020-12-27 17:02 UTC, sagararyal commented
thanks @norbertschuler 

@harshvitra android build is crashing on load. iOS doesn't have any issues.

2020-12-27 19:32 UTC, norbertschuler commented
> @harshvitra android build is crashing on load. iOS doesn't have any issues.

Android seems to have problems generating the bundle file I assume. We need to check the release build process locally. Either the upgrade of the Gradle build system or the new Auth0 integration is probably causing this.

2020-12-28 10:32 UTC, norbertschuler commented
> Update: The bundle file got build locally for me, but it is not copied into the APK file afterwards. Something in the Android build process is broken.

I just pushed a fix for the Android build with newest Gradle version by upgrading to [React-Native 0.63.4](https://github.com/react-native-community/releases/blob/master/CHANGELOG.md). Also I have updated the iOS Pods and fixed a problem with the iOS build if you have comments in your .env file by downgrading [react-native-config from version 1.4.1 to version 1.4.0](https://github.com/luggit/react-native-config/issues/522).

2020-12-28 11:43 UTC, norbertschuler commented
- [ ] Does not work if you continue as guest and then want to login clicking on "Compete" or "Me" afterwards. Then the app got stuck with this screen:
<img width="307" alt="Bildschirmfoto 2020-12-28 um 12 41 03" src="https://user-images.githubusercontent.com/1532418/103212038-65388380-493c-11eb-8fe9-8c118b46cac1.png">

2020-12-28 11:53 UTC, norbertschuler commented
- [ ] On iOS with the development environment Auth0 is not working because of this error:

<img width="352" alt="Bildschirmfoto 2020-12-28 um 12 49 09" src="https://user-images.githubusercontent.com/1532418/103212645-f9efb100-493d-11eb-8dcc-d1f6dd2008b4.png">

2020-12-28 12:03 UTC, norbertschuler commented
- [ ] On iOS with the staging environment I got this error when trying to login (testing direct login with mail and Google-Auth0):

![Simulator Screen Shot - iPhone 12 - 2020-12-28 at 12 56 21](https://user-images.githubusercontent.com/1532418/103213107-48ea1600-493f-11eb-98a2-dae592dba315.png)

2020-12-28 12:21 UTC, norbertschuler commented
- [ ] On Android the Auth0 dialog does not load for staging while working for develop:

![Screenshot_1609157964](https://user-images.githubusercontent.com/1532418/103213965-cd3d9880-4941-11eb-9ba7-28056018f655.png)![Screenshot_1609157864](https://user-images.githubusercontent.com/1532418/103213966-ce6ec580-4941-11eb-8e2e-a3478d899cf6.png)

2020-12-28 12:31 UTC, norbertschuler commented
- [ ] On Android for the development environment I can not login either with mail or google-oauth2). The login dialog does not continue or redirect back to the app.

![Screenshot_1609158647](https://user-images.githubusercontent.com/1532418/103214528-3c67bc80-4943-11eb-9afe-ac2d20b2f90d.png)

2021-01-01 18:29 UTC, norbertschuler commented
- [ ] On development environment the login with my PFTP-account currently fails with the following error:
```
backend.js:32 Possible Unhandled Promise Rejection (id: 0):
a0.response.invalid: unknown error
a0.response.invalid: unknown error
    at responseHandler (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:223617:11)
    at tryCallOne (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:3483:14)
    at http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:3584:17
    at http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:30746:21
    at _callTimer (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:30634:9)
    at _callImmediatesPass (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:30673:7)
    at MessageQueue.callImmediates [as _immediatesCallback] (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:30890:14)
    at MessageQueue.__callImmediates (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:2777:16)
    at http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:2563:18
    at MessageQueue.__guard (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:2760:13)
```

2021-01-04 21:52 UTC, norbertschuler commented
> ... fails with the following error if I run the app in debugging mode:
> 
> ```
> backend.js:32 Possible Unhandled Promise Rejection (id: 0):
> a0.response.invalid: unknown error

For some weirds reason this error (Auth0 call returns empty content despite the API status code is 200) only happens when you are using the app in debug mode while otherwise it correctly returns the credentials.

> Without the debugging enabled, I get this error message after login (after reloading the app I am successfully logged in):

I _fixed_ this problem by suppressing routing with `updateRoute` if not route was given. I do not know yet where the `updateRoute` function got called without any given route. Must be a side-effect I have not found yet.

2021-01-05 12:01 UTC, norbertschuler commented on app/actions/auth0Actions.js
> +const auth0 = new Auth0({ domain: Config.AUTH0_DOMAIN, clientId: Config.AUTH0_CLIENT_ID });
Well, this abstraction was only necessary for having a common config context for the old web client and the native apps. It's not necessary now anymore that the web client code is deprecated.

2021-01-05 12:11 UTC, norbertschuler commented
- [ ] On iOS both for signup/login and also for logout the following alert dialog is presented to the users again and again. I am not sure if it's possible to suppress it, so we maybe have to deal with it:

![Simulator Screen Shot - iPhone 12 - 2021-01-05 at 12 57 57](https://user-images.githubusercontent.com/1532418/103644909-bc1c0980-4f89-11eb-8f50-8713ff7b1d46.png)

2021-01-05 13:43 UTC, norbertschuler commented
- [ ] The signup process is as following on iOS - currently I am not able to finish the signup other then reloading the app:

1. Entering email/password on Auth0 signup dialog
2. Entering profile data + email again on our own signup dialog - can we somehow get and fill the email field from Auth0 as in our website registration as otherwise we get in trouble (see the following issues)?
3. Signup confirmation indicating to wait for an email with a link to confirm the email address from Auth0.
- **This email is not taken from step 2 if the user has entered a different email address there - the email entered at step 2 is stored only in our backend and will be never confirmed.**
- The link in the confirmation mail from Auth0 is e.g. `https://pftp.eu.auth0.com/u/email-verification?ticket=2eonnnxrJFjhT9RmZQ3jSrI0BVr00zfi#` and redirecting (Code 302) to e.g. `org.plant-for-the-planet.app://pftp.eu.auth0.com?email=norbert.schuler%40epublica.de&message=This%20URL%20can%20be%20used%20only%20once&success=false` - **that link with a custom scheme is only available on the mobile device with the app and not working on another device (showing a blank page) to confirm the mail address** - maybe we should change it towards using protocol `https` and also support the callback with our website?
- If you copy the link from the Auth0 confirmation mail into the browser on your mobile device it opens the app, but still shows the last screen shown in the app, e.g. the screen shown in this step 3 - we should make the app aware of this (deep) link and show the user profile or starting page for a logged in user instead.
- **The app does not care if the email was confirmed or not.** After killing and reloading the app, the user is logged in and can do everything.
4. If you go back from the message of step 3 twice or once to step 2 and click `Login` you **always end up with a loading screen**.
5. If the email entered at step 2 differs from step 3 reloading the app fails to load as the API call to load the user profile will say the requested user does not yet exists in the backend as the mail address does not match (code 303).

![Simulator Screen Shot - iPhone 12 - 2021-01-05 at 13 24 40](https://user-images.githubusercontent.com/1532418/103648127-f2a85300-4f8e-11eb-9a22-a0d9a7d4bb78.png)![Simulator Screen Shot - iPhone 12 - 2021-01-05 at 13 21 31](https://user-images.githubusercontent.com/1532418/103648143-f8059d80-4f8e-11eb-8b3a-50e1bc520dc2.png)![Simulator Screen Shot - iPhone 12 - 2021-01-05 at 13 22 14](https://user-images.githubusercontent.com/1532418/103648169-ffc54200-4f8e-11eb-80e0-0c08041b3c4d.png)![Simulator Screen Shot - iPhone 12 - 2021-01-05 at 13 22 35](https://user-images.githubusercontent.com/1532418/103648172-005dd880-4f8f-11eb-8534-78ed37b474b0.png)

2021-01-05 13:43 UTC, norbertschuler commented
- [ ] The current page for changing the mail address and for changing the password does not make sense anymore as it changes the mail address and password only within the backend and not for Auth0!

![Simulator Screen Shot - iPhone 12 - 2021-01-05 at 14 41 02](https://user-images.githubusercontent.com/1532418/103653056-8d586000-4f96-11eb-844e-07c99edce05d.png)

2021-01-06 08:43 UTC, norbertschuler commented on app/containers/Authentication/SignUpContainer.js
> +          formValue.email = res.email;
I debugged this by entering norbert.schuler@epublica.de at Auth0 and norbert.schuler2@epublica.de in the signup form of our app. The value of `res.email` was `norbert.schuler@epublica.de`, but after executing this line the value of `formValue.email` remained `norbert.schuler2@epublica.de` and was **not** changed! I also suggest not just patching the mail at submitting the form, but also disable the field in the UI and prefilling it with the Auth0 value.

2021-01-06 08:50 UTC, harshvitra commented on app/containers/Authentication/SignUpContainer.js
> +          formValue.email = res.email;
I tried it earlier and it wasn't working and creating other errors, hence added this hack for now.

2021-01-06 08:57 UTC, harshvitra commented
> * [ ]  The current page for (1) changing the mail address or (2) changing the password and (3) deleting the own account does not make sense anymore as it changes the mail address and password only within the backend and not for Auth0!

Hiding this section completely

2021-01-06 09:05 UTC, norbertschuler commented on app/containers/Authentication/SignUpContainer.js
> +          formValue.email = res.email;
Yes, but the hack does not work for me. The mail is not changed.

2021-01-06 09:23 UTC, norbertschuler commented
> * [x]  If you press `Cancel` on this dialog at logout you got stuck in the app showing the loading screen!

This does not happen with https://github.com/Plant-for-the-Planet-org/treecounter-app/pull/2914/commits/72d532e29e60db84b25fa7dd2dc7c33c4c74e609

2021-01-06 09:40 UTC, norbertschuler commented
> * [x]  If you press `Cancel` on this dialog at logout you got stuck in the app showing the loading screen!

Fixed with https://github.com/Plant-for-the-Planet-org/treecounter-app/pull/2914/commits/b6526d8d3a1acb7b1a03196d9d01268937fc8c4e

2021-01-06 10:21 UTC, harshvitra commented on app/containers/Authentication/SignUpContainer.js
> +          formValue.email = res.email;
Added the email from Auth0 in the field with 4aa4119

2021-01-06 14:47 UTC, norbertschuler commented
- [x] I tried to mark the email field as `editable: false`, but it did not work with the _tcomb_ form, so I marked it as `hidden: true` instead to avoid letting users edit it and get irritated if the edited value is not stored.
- [ ] The wording and the functionality on the registration confirmation page should be changed as hitting the resent button always trigger another mail to be sent from the backend.
 
![Simulator Screen Shot - iPhone 11 - 2021-01-06 at 15 39 27](https://user-images.githubusercontent.com/1532418/103780831-1c817880-5068-11eb-8ec4-8ca32873653a.png)![Simulator Screen Shot - iPhone 11 - 2021-01-06 at 15 40 08](https://user-images.githubusercontent.com/1532418/103780836-1db2a580-5068-11eb-82ae-77ddce891d53.png)![Simulator Screen Shot - iPhone 11 - 2021-01-06 at 15 40 13](https://user-images.githubusercontent.com/1532418/103780839-1db2a580-5068-11eb-92a4-c7d5fe77be6d.png)

- [ ] The backend currently wants to sent a confirmation mail and also further mails if the user clicks on resend - this must be changed.

<img width="599" alt="Bildschirmfoto 2021-01-06 um 15 40 38" src="https://user-images.githubusercontent.com/1532418/103781244-ab8e9080-5068-11eb-8be7-bb0dd124f444.png">

2021-01-07 21:33 UTC, norbertschuler commented
About the new flow which is nice as it is simpler than the Auth0 dialog (with the annoying additional warning on iOS):
- [ ] The new flow does not allow me to logout other than login with another account, does it?
- [ ] The new flow does not support login with social accounts as e.g. Apple or Facebook as we do on the website, does it? So all the user who have used these methods cannot use our app - can they? (Btw. hopefully Apple does not reject our app if we do not offer Apple Login which is mandatory on iOS if offering other SSO methods. But this solution of course does not look like a SSO.)
- [ ] If the user choose "Create account" the following dialog for entering an email always says "Login" - this might irritate users who want to sign up for the first time - the same dialog appears if the user tests the app as guests and then open the "me" or "competition" tab - maybe we should just change the screen title and button wording to "Login or Signup"?
![Simulator Screen Shot - iPhone 11 - 2021-01-07 at 22 20 27](https://user-images.githubusercontent.com/1532418/103946381-1a531300-5169-11eb-878b-75e6c0933f2e.png)

2021-01-07 21:49 UTC, norbertschuler requested changes
Translation resources missing.

2021-01-07 21:49 UTC, norbertschuler commented on app/components/Authentication/Login/OTPCode.native.js
> +                    Enter Code
Please add translation resources.

2021-01-07 21:49 UTC, norbertschuler commented on app/components/Authentication/Login/OTPCode.native.js
> +                      label={'Enter Code'}
Please add translation resources.

2021-01-07 21:49 UTC, norbertschuler commented on app/components/Authentication/Login/OTPCode.native.js
> +                      Please enter the code sent on your email.
Please add translation resources.

2021-01-07 21:49 UTC, norbertschuler commented on app/components/Authentication/Login/OTPCode.native.js
> +                            Submit Code
Please add translation resources.

2021-01-07 21:49 UTC, norbertschuler commented on app/components/Authentication/Login/OTPCode.native.js
> +                              Submit Code
Please add translation resources.

2021-01-08 10:18 UTC, norbertschuler approved these changes

2021-01-08 10:27 UTC, norbertschuler submitted a review, later dismissed

2021-01-08 10:27 UTC, norbertschuler commented on app/actions/auth0Actions.js
> +    })
This always sends an email with English language. The [Auth0 hook](https://manage.auth0.com/dashboard/eu/pftp/hooks) I setup to retrieve the render language does not work with this flow.

We might can check if https://github.com/auth0/react-native-auth0/blob/15a12d5931495008433dbef1b8fba7e7bc2ac1b7/src/auth/index.js#L235 allows any parameters to define the users language (this is calling the Auth0 API https://auth0.com/docs/api/authentication#passwordless).

2021-01-08 11:00 UTC, norbertschuler commented on app/actions/auth0Actions.js
> +    })
I tried to add 
```
      authParams: {
        ui_locales: 'de',
      },
```
but it has not helped. All the newly registered users get the `user_metadata = { "lang": "en" }` now.

2021-01-08 12:05 UTC, norbertschuler commented on app/actions/auth0Actions.js
> +    })
I found this, but I assume, I can not manipulate the bare header of the Auth0 API request using the react-native-auth0 module: https://github.com/auth0/auth0.js/issues/813

2021-01-08 14:51 UTC, norbertschuler commented on app/actions/auth0Actions.js
> +    })
I opened a support issue in the Auth0 community for this problem: https://community.auth0.com/t/no-context-renderlanguage-or-context-request-language-in-pre-user-registration-hook-after-passwordless-start/55894?u=norbert.schuler

2021-01-09 13:13 UTC, norbertschuler commented on app/actions/auth0Actions.js
> +    })
Btw. we should be aware we are creating multiple accounts at Auth0 using different login/signup methods: 
<img width="1013" alt="Bildschirmfoto 2021-01-09 um 13 58 45" src="https://user-images.githubusercontent.com/1532418/104092521-0d443a00-52b7-11eb-9fc5-799d5541620f.png">

2021-01-11 11:53 UTC, norbertschuler commented on app/actions/auth0Actions.js
> +    })
So if we want to go forward fast, we can change the email templates to just contains both German and English language for everybody if we cannot find out the user's language yet.

2021-01-11 13:25 UTC, norbertschuler commented on app/actions/auth0Actions.js
> +    })
Using https://auth0.com/docs/connections/passwordless/guides/email-otp to solve this now. Thanks @sagararyal

2021-01-11 13:39 UTC, norbertschuler commented
- [ ] If you use the back arrow (in my iOS 11 simulator) from the screen where you should enter your code, you get back to the screen to enter you email, but the "next" button is disabled. Also changing the email address does not enable the button again:

![Simulator Screen Shot - iPhone 11 - 2021-01-11 at 14 35 41](https://user-images.githubusercontent.com/1532418/104189091-ca1bcf80-544c-11eb-9690-248ced991dc6.png)

2021-01-11 15:06 UTC, norbertschuler commented
- [ ] if you used you account at first with Auth0 on the native app, Auth0 is creating an account of type email and that has not password. So login with password does not work in the web. Unfortunately logging in with Google-Oauth also does not work showing “The user does not exist” :-(

<img width="1036" alt="Bildschirmfoto 2021-01-11 um 15 14 31" src="https://user-images.githubusercontent.com/1532418/104198604-03f2d300-5459-11eb-9ea4-7e2dcff16705.png">

<img width="322" alt="Bildschirmfoto 2021-01-11 um 15 13 43" src="https://user-images.githubusercontent.com/1532418/104198737-27b61900-5459-11eb-9c7c-7b5a137dbab1.png"><img width="360" alt="Bildschirmfoto 2021-01-11 um 15 13 00" src="https://user-images.githubusercontent.com/1532418/104198740-28e74600-5459-11eb-8d87-66f08692800e.png">

2021-01-11 15:10 UTC, norbertschuler commented
- [ ] The other way around (register first for and old account with Auth0 on the webapp with Google-Auth0 or email/password) also has a problem for me. The first confirmation code I get trying afterwards to login into the native iOS app is rejected as invalid. I had to try again sending another code which then make the login succeed :-(

<img width="1049" alt="Bildschirmfoto 2021-01-11 um 15 19 21" src="https://user-images.githubusercontent.com/1532418/104199158-a9a64200-5459-11eb-858d-171b186bac96.png">

<img width="1027" alt="Bildschirmfoto 2021-01-11 um 15 20 33" src="https://user-images.githubusercontent.com/1532418/104199116-9f844380-5459-11eb-8b41-a08581280af3.png">

![Simulator Screen Shot - iPhone 11 - 2021-01-11 at 15 18 48](https://user-images.githubusercontent.com/1532418/104199233-c5114d00-5459-11eb-9c2f-e8424de3c57a.png)

2021-01-13 10:06 UTC, norbertschuler commented
- [ ] If you press the "next" button on the email input screen without entering an email, the button shows an activity indicator and despite what you enter for the mail address, you can not submit the form anymore again:

![Screenshot_1610532252](https://user-images.githubusercontent.com/1532418/104437696-b5147d00-55c1-11eb-92a7-60d35b1c8de7.png)

2021-01-13 10:43 UTC, norbertschuler commented on app/actions/signupActions.js
> +        } else {
@harshvitra Do we wait for a backend change to return `data.activated: true` here in order to avoid showing any confirmation screen in the frontend?

<img width="642" alt="Bildschirmfoto 2021-01-13 um 11 40 16" src="https://user-images.githubusercontent.com/1532418/104441651-8947c600-55c6-11eb-935a-e964cf609a3e.png">

2021-01-14 18:01 UTC, norbertschuler commented on app/actions/signupActions.js
> +        } else {
We just missed to send the already stored OAuth token with a header. I fixed the postRequest not using the `authentificated: true` flag yet.

2021-01-14 20:49 UTC, norbertschuler submitted a review, later dismissed
Now I still have problem calling the changed `loadUserProfile` at some places.

2021-01-14 20:49 UTC, norbertschuler commented on app/actions/signupActions.js
> +          }));
This does not work anymore after I changed `loadUserProfile` - how can we make it work again?

2021-01-14 20:49 UTC, norbertschuler commented on app/actions/signupActions.js
> +        }));
This probably won't work either, but is not used anymore.

2021-01-14 20:49 UTC, norbertschuler commented on app/actions/authActions.js
> +          }));
This probably won't work either, but is not used anymore.

2021-01-14 20:49 UTC, norbertschuler commented on app/actions/redemptionAction.js
> +            })
This probably won't work anymore. Might be used and should be fixed.

2021-01-15 09:53 UTC, norbertschuler approved these changes
Not yet perfect, but I assume good to go. Currently still showing a login page for a second after signup before going to the home screen as the async executed API call to load the users profile might be delayed.

2021-01-15 11:07 UTC, merged